FROM python:3.10-bullseye

ENV DEBIAN_FRONTEND noninteractive

# Cài đặt Java
RUN apt-get update
RUN apt-get install -y openjdk-11-jdk

# Cài đặt Spark
RUN wget https://downloads.apache.org/spark/spark-3.5.0/spark-3.5.0-bin-hadoop3.tgz
RUN tar -xzf spark-3.5.0-bin-hadoop3.tgz && \
  mv spark-3.5.0-bin-hadoop3 /opt/spark

# Cài đặt PySpark
RUN pip install pyspark==3.5.0

# Đặt biến môi trường cho Spark và Python
ENV SPARK_HOME=/opt/spark
ENV PATH=$PATH:$SPARK_HOME/bin:$SPARK_HOME/sbin
ENV PYSPARK_PYTHON=/usr/local/bin/python

# Tạo thư mục để lưu trữ các ứng dụng Spark
RUN mkdir /opt/spark-applications

# Mở các cổng cần thiết cho Spark
EXPOSE 8080 7077 4040

# Cấu hình lệnh để khởi động Spark Master khi khởi tạo container
CMD ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]